### ISSUE TITLE
kernel_shape is wrong

### ISSUE THREAD

**Issue by fangwudi** [alexandrosstergiou/keras-DepthwiseConv3D#6]
in kernel shape, dim of group_num is missing .
I correct it as https://github.com/fangwudi/Group-Depthwise-Conv3D-for-Keras

**Comment by alexandrosstergiou** [comment]
Reading though your implementation (and understanding correctly), your concern is based on --3D-- kernels for grouped convolutions.

The aim of the current repository is to provide a custom layer for **depth-wise (i.e. channel-wise) convolutions** in 3D, which can also enable the use separable convolutions in volumetric inputs. These are **not to be confused with grouped convolutions** as seen in architectures such as ResneXt and performed in parallel, since I find that they have been adequately addressed without the need of separate Keras layers [link to code snipet](https://github.com/titu1994/Keras-ResNeXt/blob/e4b7a17482c1b2bc5f00b89a8820625d8bf4ce90/resnext.py#L363-L371). 

To avoid any confusion, I have re-named a few variables throughout the code to make it easier to follow.

Best,
